export const NewCollectionUrl = [
  { image: "/new-collection/new-collection-2.png", alt: "new-collection-2" },
  { image: "/new-collection/new-collection-1.png", alt: "new-collection-1" },
  { image: "/new-collection/new-collection-2.png", alt: "new-collection-2" },
  { image: "/new-collection/new-collection-1.png", alt: "new-collection-1" },
  { image: "/new-collection/new-collection-2.png", alt: "new-collection-2" },
  { image: "/new-collection/new-collection-1.png", alt: "new-collection-1" },
  { image: "/new-collection/new-collection-2.png", alt: "new-collection-2" },
  { image: "/new-collection/new-collection-1.png", alt: "new-collection-1" },
];

export const NewThisWeekUrl = [
  {
    image: "/new-this-week/new-this-week-1.png",
    alt: "new-this-week-1",
    title: "V-Neck Shirt",
    desc: "Embroidered Seersucker Shirt",
    price: "$ 99",
  },
  {
    image: "/new-this-week/new-this-week-2.png",
    alt: "new-this-week-2",
    title: "Cotton T Shirt",
    desc: "Basic Slim Fit T-Shirt",
    price: "$ 99",
  },
  {
    image: "/new-this-week/new-this-week-3.png",
    alt: "new-this-week-3",
    title: "Henley T-Shirt",
    desc: "Blurred Print T-Shirt",
    price: "$ 129",
  },
  {
    image: "/new-this-week/new-this-week-4.png",
    alt: "new-this-week-4",
    title: "Crewneck T-Shirt",
    desc: "Full Sleeve Zipper",
    price: "$ 89,99",
  },
  {
    image: "/new-this-week/new-this-week-1.png",
    alt: "new-this-week-1",
    title: "V-Neck Shirt",
    desc: "Embroidered Seersucker Shirt",
    price: "$ 99",
  },
  {
    image: "/new-this-week/new-this-week-2.png",
    alt: "new-this-week-2",
    title: "Cotton T Shirt",
    desc: "Basic Slim Fit T-Shirt",
    price: "$ 99",
  },
  {
    image: "/new-this-week/new-this-week-3.png",
    alt: "new-this-week-3",
    title: "Henley T-Shirt",
    desc: "Blurred Print T-Shirt",
    price: "$ 129",
  },
  {
    image: "/new-this-week/new-this-week-4.png",
    alt: "new-this-week-4",
    title: "Crewneck T-Shirt",
    desc: "Full Sleeve Zipper",
    price: "$ 89,99",
  },
  {
    image: "/new-this-week/new-this-week-1.png",
    alt: "new-this-week-1",
    title: "V-Neck Shirt",
    desc: "Embroidered Seersucker Shirt",
    price: "$ 99",
  },
  {
    image: "/new-this-week/new-this-week-2.png",
    alt: "new-this-week-2",
    title: "Cotton T Shirt",
    desc: "Basic Slim Fit T-Shirt",
    price: "$ 99",
  },
  {
    image: "/new-this-week/new-this-week-3.png",
    alt: "new-this-week-3",
    title: "Henley T-Shirt",
    desc: "Blurred Print T-Shirt",
    price: "$ 129",
  },
  {
    image: "/new-this-week/new-this-week-4.png",
    alt: "new-this-week-4",
    title: "Crewneck T-Shirt",
    desc: "Full Sleeve Zipper",
    price: "$ 89,99",
  },
  {
    image: "/new-this-week/new-this-week-1.png",
    alt: "new-this-week-1",
    title: "V-Neck Shirt",
    desc: "Embroidered Seersucker Shirt",
    price: "$ 99",
  },
  {
    image: "/new-this-week/new-this-week-2.png",
    alt: "new-this-week-2",
    title: "Cotton T Shirt",
    desc: "Basic Slim Fit T-Shirt",
    price: "$ 99",
  },
  {
    image: "/new-this-week/new-this-week-3.png",
    alt: "new-this-week-3",
    title: "Henley T-Shirt",
    desc: "Blurred Print T-Shirt",
    price: "$ 129",
  },
  {
    image: "/new-this-week/new-this-week-4.png",
    alt: "new-this-week-4",
    title: "Crewneck T-Shirt",
    desc: "Full Sleeve Zipper",
    price: "$ 89,99",
  },
];
